services:

  app:
    build:
      context: ./backend/.
    env_file:
      - .env
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - /app/node_modules
      - ./backend:/app
    command: >
      sh -c  "npm run start:dev" 

  client:
    build:
      context: ./frontend/.
    restart: always
    depends_on:
      - app
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    command: >
      sh -c  "npm run start" 
